Repository terraform-providers/terraform-provider-jdcloud, pull requests merged in 2019-07, with the labels that each got.

#10 modify go.mod
  go.mod
  vendor/github.com/jdcloud-api/jdcloud-sdk-go/go.mod
Labels: dependencies, size/XS

#11 Remove broken link
  website/jdcloud.erb
Labels: documentation, size/XS

#12 Tweak CI and GNUmakefile to better fit go modules
  .travis.yml
  GNUmakefile
Labels: size/XS

#13 docs: Formalize inline HCL codes to canonical format
  website/docs/jdcloud_availability_group.html.markdown
  website/docs/jdcloud_disk_attachment.html.markdown
  website/docs/jdcloud_eip.html.markdown
  website/docs/jdcloud_eip_association.html.markdown
  website/docs/jdcloud_network_interface.html.markdown
  website/docs/jdcloud_network_interface_attachment.html.markdown
  website/docs/jdcloud_network_security_group.html.markdown
  website/docs/jdcloud_oss_bucket_upload.html.markdown
  website/docs/jdcloud_rds_account.html.markdown
  website/docs/jdcloud_rds_database.html.markdown
  website/docs/jdcloud_rds_instance.html.markdown
  website/docs/jdcloud_rds_privilege.html.markdown
  website/docs/jdcloud_route_table.html.markdown
  website/docs/jdcloud_route_table_rules.html.markdown
  website/docs/jdcloud_subnet.html.markdown
  website/docs/jdcloud_vpc.html.markdown
Labels: documentation, size/M
